In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [3]:
np.array([1,4,2,'5',False])

array(['1', '4', '2', '5', 'False'], dtype='<U11')

In [4]:
sample_list = [1,4,2,'5',False]

In [5]:
sample_list

[1, 4, 2, '5', False]

In [6]:
sample_list * 2

[1, 4, 2, '5', False, 1, 4, 2, '5', False]

In [17]:
np_array1 = np.array([1,4,2,5])

In [18]:
np_array1

array([1, 4, 2, 5])

In [19]:
np_array1 * 2

array([ 2,  8,  4, 10])

In [20]:
np_array1 + 3

array([4, 7, 5, 8])

In [21]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

In [22]:
a = np.array(a)

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a[0][1]

2

In [84]:
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [85]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [89]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [90]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [94]:
np.full((3,3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [95]:
np.full((5,5), 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [96]:
mat_1 = np.array([[1,2,3],
                  [4,5,6]])

In [97]:
mat_2 = np.array([[7,8,9],
                  [10,11,12]])

In [98]:
matrix_combine_rowwise = np.concatenate([mat_1,mat_2], axis=0)
matrix_combine_rowwise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
matrix_combine_columnwise = np.concatenate([mat_1,mat_2],axis=1)
matrix_combine_columnwise

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])